# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cleanAngles <- function(as) {
    .Call('mta2_cleanAngles', PACKAGE = 'mta2', as)
}

distMat <- function(x, y, power = 2L) {
    .Call('mta2_distMat', PACKAGE = 'mta2', x, y, power)
}

distMatV <- function(x, y, power = 2L) {
    .Call('mta2_distMatV', PACKAGE = 'mta2', x, y, power)
}

distMat3d <- function(x, y, z, power = 2L) {
    .Call('mta2_distMat3d', PACKAGE = 'mta2', x, y, z, power)
}

distMat3dV <- function(x, y, z, power = 2L) {
    .Call('mta2_distMat3dV', PACKAGE = 'mta2', x, y, z, power)
}

computeNorm <- function(r) {
    .Call('mta2_computeNorm', PACKAGE = 'mta2', r)
}

gaussBlurSlow <- function(source, target, w, h, r) {
    .Call('mta2_gaussBlurSlow', PACKAGE = 'mta2', source, target, w, h, r)
}

gaussBlur <- function(source, target, w, h, r) {
    .Call('mta2_gaussBlur', PACKAGE = 'mta2', source, target, w, h, r)
}

boxBlur <- function(source, target, w, h, r) {
    .Call('mta2_boxBlur', PACKAGE = 'mta2', source, target, w, h, r)
}

getAngleP <- function(x, y) {
    .Call('mta2_getAngleP', PACKAGE = 'mta2', x, y)
}

getAngleV <- function(x, y) {
    .Call('mta2_getAngleV', PACKAGE = 'mta2', x, y)
}

getAnglesP <- function(xs, ys) {
    .Call('mta2_getAnglesP', PACKAGE = 'mta2', xs, ys)
}

getAnglesV <- function(xs, ys) {
    .Call('mta2_getAnglesV', PACKAGE = 'mta2', xs, ys)
}

getLength <- function(x, y) {
    .Call('mta2_getLength', PACKAGE = 'mta2', x, y)
}

getLength3d <- function(x, y, z) {
    .Call('mta2_getLength3d', PACKAGE = 'mta2', x, y, z)
}

getLengths <- function(xs, ys) {
    .Call('mta2_getLengths', PACKAGE = 'mta2', xs, ys)
}

getLengths3d <- function(xs, ys, zs) {
    .Call('mta2_getLengths3d', PACKAGE = 'mta2', xs, ys, zs)
}

getVelocity <- function(x, y) {
    .Call('mta2_getVelocity', PACKAGE = 'mta2', x, y)
}

getVelocity3d <- function(x, y, z) {
    .Call('mta2_getVelocity3d', PACKAGE = 'mta2', x, y, z)
}

getVelocities <- function(xs, ys) {
    .Call('mta2_getVelocities', PACKAGE = 'mta2', xs, ys)
}

getVelocities3d <- function(xs, ys, zs) {
    .Call('mta2_getVelocities3d', PACKAGE = 'mta2', xs, ys, zs)
}

spatialRescale <- function(x, y, npts) {
    .Call('mta2_spatialRescale', PACKAGE = 'mta2', x, y, npts)
}

spatialRescale3d <- function(x, y, z, npts) {
    .Call('mta2_spatialRescale3d', PACKAGE = 'mta2', x, y, z, npts)
}

spatialRescaleA <- function(xs, ys, n_pts) {
    .Call('mta2_spatialRescaleA', PACKAGE = 'mta2', xs, ys, n_pts)
}

spatialRescaleAlong <- function(xs, ys, n_pts) {
    .Call('mta2_spatialRescaleAlong', PACKAGE = 'mta2', xs, ys, n_pts)
}

spatialRescaleA3d <- function(xs, ys, zs, n_pts) {
    .Call('mta2_spatialRescaleA3d', PACKAGE = 'mta2', xs, ys, zs, n_pts)
}

spatialRescaleAlong3d <- function(xs, ys, zs, n_pts) {
    .Call('mta2_spatialRescaleAlong3d', PACKAGE = 'mta2', xs, ys, zs, n_pts)
}

trajAlign <- function(xs, ys, start, end, coordinates) {
    .Call('mta2_trajAlign', PACKAGE = 'mta2', xs, ys, start, end, coordinates)
}

trajAlign3d <- function(xs, ys, zs, start, end, coordinates) {
    .Call('mta2_trajAlign3d', PACKAGE = 'mta2', xs, ys, zs, start, end, coordinates)
}

